services:
  meilisearch-dev:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=development
      - MEILI_HOST
      - MEILI_MASTER_KEY
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped

  postgres-dev:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
volumes:
  postgres_data:
