// Interface automatically generated by schemas-to-ts

export interface BlogPage {
  id: number;
  attributes: {
    createdAt: Date,
    updatedAt: Date,
    publishedAt?: Date,
    Title: string,
    Introduction?: string,
  };
}
export interface BlogPage_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  Introduction?: string;
}

export interface BlogPage_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  Introduction?: string;
}

export interface BlogPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  Introduction?: string;
}
